import type { TabInfo, TabInfoWithoutFavIconUrl } from "../types";

export const mockData: TabInfoWithoutFavIconUrl[] = [
  {
    id: 1,
    title: "Link Map",
    url: "chrome-extension://jappgmhllahigjolfpgbjdfhciabdnde/tree.html",
    parent: null,
  },
  {
    id: 2,
    title: "API reference - Chrome Developers",
    url: "https://developer.chrome.com/docs/extensions/reference/",
    parent: 1,
  },
  {
    id: 3,
    title: "chrome.desktopCapture - Chrome Developers",
    url: "https://developer.chrome.com/docs/extensions/reference/desktopCapture/",
    parent: 2,
  },
  {
    id: 4,
    title: "chrome extension development screenshot - Google Search",
    url: "https://www.google.com/search?q=chrome+extension+development+screenshot&sourceid=chrome&ie=UTF-8",
    parent: 3,
  },
  {
    id: 5,
    title: "chrome.omnibox - Chrome Developers",
    url: "https://developer.chrome.com/docs/extensions/reference/omnibox/",
    parent: 2,
  },
  {
    id: 6,
    title: "chrome.tabs - Chrome Developers",
    url: "https://developer.chrome.com/docs/extensions/reference/tabs/#method-move",
    parent: 2,
  },
  {
    id: 7,
    title: "chrome.tabs - Chrome Developers",
    url: "https://developer.chrome.com/docs/extensions/reference/tabs/#method-captureVisibleTab",
    parent: 6,
  },
  {
    id: 8,
    title: "chrome.extensionTypes - Chrome Developers",
    url: "https://developer.chrome.com/docs/extensions/reference/extensionTypes/#type-ImageDetails",
    parent: 6,
  },
  {
    id: 9,
    title: "chrome.management - Chrome Developers",
    url: "https://developer.chrome.com/docs/extensions/reference/management/",
    parent: 2,
  },
  {
    id: 10,
    title: "Chrome Extensions: Overriding Chrome pages - Chrome Developers",
    url: "https://developer.chrome.com/docs/extensions/mv3/override/",
    parent: 9,
  },
  {
    id: 11,
    title: "Chrome Extension examples - Chrome Developers",
    url: "https://developer.chrome.com/docs/extensions/mv3/samples/",
    parent: 10,
  },
  {
    id: 12,
    title: "YouTube",
    url: "https://www.youtube.com/",
    parent: 1,
  },
  {
    id: 13,
    title: "SvelteKit in 100 seconds - YouTube",
    url: "https://www.youtube.com/watch?v=H1eEFfAkIik",
    parent: 12,
  },
  {
    id: 14,
    title: "localhost",
    url: "http://localhost:5173/",
    parent: 12,
  },
  {
    id: 15,
    title:
      "Homeless Millionaire Experiment❤️ #socialexperiment #homeless #kindness #goodkarma - YouTube",
    url: "https://www.youtube.com/shorts/Z2IW1BbNBMQ",
    parent: 12,
  },
  {
    id: 16,
    title: "Llama 2: Full Breakdown - YouTube",
    url: "https://www.youtube.com/watch?v=zJBpRn2zTco",
    parent: 12,
  },
  {
    id: 17,
    title: "file:///Users/lukas.petry/projects/reading-helper/message.html",
    url: "file:///Users/lukas.petry/projects/reading-helper/message.html",
    parent: 12,
  },
  {
    id: 18,
    title: "Tab Control - Chrome Web Store",
    url: "https://chrome.google.com/webstore/detail/tab-control/gfeannmglnjdmnpigailhcoepplcacaf",
    parent: 1,
  },
  {
    id: 19,
    title: "QuicKey – The quick tab switcher - Chrome Web Store",
    url: "https://chrome.google.com/webstore/detail/quickey-%E2%80%93-the-quick-tab-s/ldlghkoiihaelfnggonhjnfiabmaficg",
    parent: 18,
  },
  {
    id: 20,
    title: "Tab Switcher - Chrome Web Store",
    url: "https://chrome.google.com/webstore/detail/tab-switcher/gcilookdakgpccpbcjgnpaecofklimck",
    parent: 18,
  },
  {
    id: 21,
    title: "Quick 'K' - Chrome Web Store",
    url: "https://chrome.google.com/webstore/detail/quick-k/gilkjbonaifnnghbdpjmbomjjfffabmn",
    parent: 18,
  },
  {
    id: 22,
    title: "Tab Thumbnails Switcher - Chrome Web Store",
    url: "https://chrome.google.com/webstore/detail/tab-thumbnails-switcher/jpaiaplhepeiilhiegfnknedhjepknng",
    parent: 18,
  },
  {
    id: 23,
    title: "@open-tabs-session @big-junk - WorkFlowy",
    url: "https://workflowy.com/#/1d2f686293e3",
    parent: 1,
  },
  {
    id: 24,
    title: "The Rise of the AI Engineer - by swyx - Latent Space",
    url: "https://www.latent.space/p/ai-engineer?utm_source=the-ai-exchange&utm_medium=newsletter&utm_campaign=the-ai-ops-job-landscape",
    parent: 1,
  },
  {
    id: 25,
    title: "mytime-pi.vercel.app",
    url: "https://mytime-pi.vercel.app/",
    parent: 1,
  },
  {
    id: 26,
    title: "logout",
    url: "https://www.sska.de/de/home/misc/logout.html?n=true",
    parent: 1,
  },
  {
    id: 27,
    title: "LeaderLine",
    url: "https://anseki.github.io/leader-line/",
    parent: 1,
  },
  {
    id: 28,
    title: "Whimsical - Where great ideas take shape",
    url: "https://whimsical.com/",
    parent: 1,
  },
  {
    id: 29,
    title:
      "The Art of ChatGPT Prompting: A Guide to Crafting Clear and Effective Prompts",
    url: "https://app.gumroad.com/d/72edc9d495ad3c8b2881dbc887d3cbe9",
    parent: 1,
  },
  {
    id: 30,
    title: "Notion Academy — Getting started with Projects",
    url: "https://www.notion.so/help/notion-academy/course/getting-started-projects",
    parent: 1,
  },
  {
    id: 31,
    title: "web.arbeitsagentur.de",
    url: "https://web.arbeitsagentur.de/portal/termine/pd/",
    parent: 1,
  },
  {
    id: 32,
    title: "online.innerengineering.com",
    url: "https://online.innerengineering.com/en/course/session-1",
    parent: 1,
  },
  {
    id: 33,
    title:
      "The hardest part of building software is not coding, it's requirements - Stack Overflow Blog",
    url: "https://stackoverflow.blog/2023/06/26/the-hardest-part-of-building-software-is-not-coding-its-requirements/?utm_source=iterable&utm_medium=email&utm_campaign=the-overflow-newsletter",
    parent: 1,
  },
].map((item) => ({
  ...item,
  tabId: 0,
  windowId: 0,
  status: "openFront",
}));
